---
name: ci
on: push

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
      - run: uv sync --all-groups -v
      - run: ty check
      - run: ruff check
      - run: ruff format --check
