---
name: ci
on: push

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: eifinger/setup-rye@v4
        with:
          version: 'latest'
      - run: rye sync
      - run: ruff check
